# Generated by Django 3.0.5 on 2020-04-30 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzstva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prispevky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Částka')),
                ('datum_platby', models.DateField(help_text='Formát: RRRR-MM-DD', verbose_name='Datum platby')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=30, verbose_name='Název')),
            ],
        ),
        migrations.CreateModel(
            name='Clen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('vek', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(100)], verbose_name='Věk')),
                ('datum_vstupu', models.DateField(help_text='Formát: RRRR-MM-DD', null=True, verbose_name='Datum vstupu')),
                ('foto', models.ImageField(upload_to='', verbose_name='Fotka')),
                ('druzstvo', models.ManyToManyField(to='sk.Druzstva')),
                ('platba', models.ManyToManyField(to='sk.Prispevky')),
                ('status', models.ManyToManyField(to='sk.Status')),
            ],
        ),
    ]
