# Generated by Django 3.0.5 on 2020-04-30 17:36

from django.db import migrations, models
import sk.models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clen',
            options={'ordering': ['prijmeni'], 'verbose_name_plural': 'Člen'},
        ),
        migrations.AlterModelOptions(
            name='druzstva',
            options={'ordering': ['oznaceni'], 'verbose_name_plural': 'Družstva'},
        ),
        migrations.AlterModelOptions(
            name='prispevky',
            options={'ordering': ['castka', 'datum_platby'], 'verbose_name_plural': 'Příspěvky'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['nazev'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='clen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=sk.models.foto_path, verbose_name='Fotka'),
        ),
    ]
